name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run typecheck
    - run: npm test
    - name: Report Coveralls
      uses: coverallsapp/github-action@v2
      with:
        file: coverage/lcov.info
