name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run typecheck
    - run: npm test
    - run: npm run coverage
      env:
        COVERALLS_REPO_TOKEN: OsZTi8qvDNHjOzoii1sSir7DZPpnZ2aCU
